packages:
    "@bower/jquery-pjax":
        patterns:
            - "jquery.pjax.js"
    "@bower/headroom.js":
        patterns:
            - "dist/headroom.js"
    "@bower/font-awesome":
        patterns:
            - "css/font-awesome.css"
            - "fonts/*"
    "@bower/footable":
        patterns:
            - "fonts/*"
            - "js/footable.js"
    "@bower/bootstrap-filestyle":
        patterns:
            - "src/bootstrap-filestyle.js"
    "@bower/moment":
        patterns:
            - "moment.js"
    "@bower/hammerjs":
        patterns:
            - "hammer.js"
    "@bower/jquery-knob":
            patterns:
                - "js/jquery-knob.js"
    "@bower/select2":
        patterns:
            - "dist/js/select2.js"
    "@bower/autosize":
        patterns:
            - "dist/autosize.js"
    "@bower/sonatra-bootstrap-nav-footable":
        patterns:
            - "js/nav-footable.js"
    "@bower/sonatra-bootstrap-dropdown-position":
        patterns:
            - "js/dropdown-position.js"
    "@bower/sonatra-bootstrap-nav-scroll":
        patterns:
            - "js/nav-scroll.js"
    "@bower/sonatra-bootstrap-panel-collapse":
        patterns:
            - "js/panel-collapse.js"
    "@bower/sonatra-footable-responsive":
        patterns:
            - "js/footable-responsive.js"
    "@bower/sonatra-footable-striped":
        patterns:
            - "js/footable-striped.js"
    "@bower/sonatra-jquery-scroller":
        patterns:
            - "js/scroller.js"
            - "js/sticky-header.js"
    "@bower/sonatra-jquery-datetime-picker":
        patterns:
            - "js/datetime-picker.js"
            - "!less/*"
    "@bower/sonatra-jquery-sidebar":
        patterns:
            - "js/sidebar.js"
    "@bower/sonatra-jquery-table-pager":
        patterns:
            - "js/table-pager.js"
    "@bower/sonatra-jquery-table-pager-footable":
        patterns:
            - "js/table-pager-footable.js"
    "@bower/sonatra-jquery-table-select":
        patterns:
            - "js/table-select.js"
    "@bower/sonatra-jquery-ripple":
            patterns:
                - "js/ripple.js"
    "@bower/select2-bootstrap-theme":
        patterns:
            - "!*"
    "@bower/sonatra-select2-scroller":
        patterns:
            - "js/select2-scroller.js"
    "@bower/sonatra-select2-responsive":
        patterns:
            - "js/select2-responsive.js"
    "@bower/sonatra-theme-gluon":
        patterns:
            - "js/floating-label.js"
            - "js/resizing-textarea.js"
            - "js/table-pager-default.js"
            - "js/sidebar-context.js"
            - "js/navbar-sidebar.js"
            - "js/navbar-modal.js"
            - "js/navbar-dropdown-position.js"
            - "js/scroller-shrink.js"
            - "js/footable-destroy.js"
            - "js/jquery-headroom.js"
    "@bower/sonatra-theme-gluon-pjax":
        patterns:
            - "js/app-pjax.js"
            - "js/navbar-app-pjax.js"
            - "js/components/bootstrap-affix.js"
            - "js/components/bootstrap-modal.js"
            - "js/components/bootstrap-dropdown.js"
            - "js/components/bootstrap-scrollspy.js"
            - "js/components/bootstrap-carousel.js"
            - "js/components/bootstrap-filestyle.js"
            - "js/components/sonatra-scroller-shrink.js"
            - "js/components/sonatra-jquery-scroller.js"
            - "js/components/sonatra-jquery-scroller-sticky-header.js"
            - "js/components/sonatra-jquery-datetime-picker.js"
            - "js/components/sonatra-jquery-ripple.js"
            - "js/components/sonatra-jquery-sidebar.js"
            - "js/components/sonatra-jquery-table-pager.js"
            - "js/components/sonatra-jquery-table-pager-footable.js"
            - "js/components/sonatra-jquery-table-select.js"
            - "js/components/sonatra-jquery-headroom.js"
            - "js/components/sonatra-bootstrap-nav-scroll.js"
            - "js/components/sonatra-bootstrap-panel-collapse.js"
            - "js/components/sonatra-select2-responsive.js"
            - "js/components/sonatra-select2-scroller.js"
            - "js/components/sonatra-gluon-floating-label.js"
            - "js/components/sonatra-gluon-resizing-textarea.js"
            - "js/components/sonatra-gluon-sidebar-context.js"
            - "js/components/sonatra-gluon-navbar-sidebar.js"
            - "js/components/sonatra-gluon-navbar-modal.js"
            - "js/components/sonatra-gluon-navbar-dropdown-position.js"
    "doctrine_bundle":
        patterns:
            - !*
    "security_bundle":
        patterns:
            - !*
    "swiftmailer_bundle":
        patterns:
            - !*
    "sonatra_block_bundle":
        patterns:
            - !*
    "sonatra_bootstrap_bundle":
        patterns:
            - "!assetic/less/bootstrap.less"
    "sonatra_gluon_bundle":
        patterns:
            - "assetic/less/*"

asset_replacement:
    "@bower/bootstrap/less/bootstrap.less": "sonatra_gluon_bundle/assetic/less/bootstrap.less"
    "@bower/bootstrap/less/theme.less": "sonatra_gluon_bundle/assetic/less/bootstrap-theme.less"
    "@bower/bootstrap/dist/css/bootstrap.css": "sonatra_gluon_bundle/assetic/less/bootstrap.less"
    "@bower/bootstrap/dist/css/bootstrap-theme.css": "sonatra_gluon_bundle/assetic/less/bootstrap-theme.less"

    "sonatra_bootstrap_bundle/assetic/less/bootstrap.less": "sonatra_gluon_bundle/assetic/less/bootstrap.less"
    "sonatra_bootstrap_bundle/assetic/less/bootstrap-extensions.less": "sonatra_gluon_bundle/assetic/less/bootstrap-theme.less"

    "@bower/sonatra-bootstrap-dropdown-position/less/dropdown-position.less": "sonatra_gluon_bundle/assetic/less/bootstrap-dropdown-position.less"

    "@bower/sonatra-bootstrap-nav-scroll/less/nav-scroll.less": "sonatra_gluon_bundle/assetic/less/bootstrap-nav-scroll.less"

    "@bower/sonatra-bootstrap-panel-collapse/less/panel-collapse.less": "sonatra_gluon_bundle/assetic/less/bootstrap-panel-collapse.less"

    "@bower/footable/less/footable.core.less": "sonatra_gluon_bundle/assetic/less/footable.less"
    "@bower/footable/css/footable.core.css": "sonatra_gluon_bundle/assetic/less/footable.less"

    "@bower/sonatra-footable-striped/less/footable-striped.less": "sonatra_gluon_bundle/assetic/less/footable-striped.less"
    "@bower/sonatra-footable-striped/css/footable-striped.css": "sonatra_gluon_bundle/assetic/less/footable-striped.less"

    "@bower/sonatra-jquery-ripple/less/ripple.less": "sonatra_gluon_bundle/assetic/less/jquery-ripple.less"
    "@bower/sonatra-jquery-ripple/css/ripple.css": "sonatra_gluon_bundle/assetic/less/jquery-ripple.less"

    "@bower/sonatra-jquery-scroller/less/scroller.less": "sonatra_gluon_bundle/assetic/less/jquery-scroller.less"
    "@bower/sonatra-jquery-scroller/css/scroller.css": "sonatra_gluon_bundle/assetic/less/jquery-scroller.less"

    "@bower/sonatra-jquery-datetime-picker/less/datetime-picker.less": "sonatra_gluon_bundle/assetic/less/jquery-datetime-picker.less"
    "@bower/sonatra-jquery-datetime-picker/css/datetime-picker.css": "sonatra_gluon_bundle/assetic/less/jquery-datetime-picker.less"

    "@bower/sonatra-jquery-sidebar/less/sidebar.less": "sonatra_gluon_bundle/assetic/less/jquery-sidebar.less"
    "@bower/sonatra-jquery-sidebar/css/sidebar.css": "sonatra_gluon_bundle/assetic/less/jquery-sidebar.less"
    "@bower/sonatra-jquery-sidebar/less/sidebar-bootstrap.less": "sonatra_gluon_bundle/assetic/less/jquery-sidebar.less"
    "@bower/sonatra-jquery-sidebar/css/sidebar-bootstrap.css": "sonatra_gluon_bundle/assetic/less/jquery-sidebar.less"

    "@bower/sonatra-jquery-table-pager/less/table-pager.less": "sonatra_gluon_bundle/assetic/less/jquery-table-pager.less"
    "@bower/sonatra-jquery-table-pager/css/table-pager.css": "sonatra_gluon_bundle/assetic/less/jquery-table-pager.less"
    "@bower/sonatra-jquery-table-pager/less/table-sort.less": "sonatra_gluon_bundle/assetic/less/jquery-table-sort.less"
    "@bower/sonatra-jquery-table-pager/css/table-sort.css": "sonatra_gluon_bundle/assetic/less/jquery-table-sort.less"

    "@bower/sonatra-jquery-table-select/less/table-select.less": "sonatra_gluon_bundle/assetic/less/jquery-table-select.less"
    "@bower/sonatra-jquery-table-select/css/table-select.css": "sonatra_gluon_bundle/assetic/less/jquery-table-select.less"

    "@bower/select2-bootstrap-theme/src/build.less": "sonatra_gluon_bundle/assetic/less/select2-bootstrap-theme.less"
    "@bower/select2-bootstrap-theme/dist/select2-bootstrap.css": "sonatra_gluon_bundle/assetic/less/select2-bootstrap-theme.less"

    "@bower/sonatra-select2-responsive/less/select2-responsive.less": "sonatra_gluon_bundle/assetic/less/select2-responsive.less"
    "@bower/sonatra-select2-responsive/css/select2-responsive.css": "sonatra_gluon_bundle/assetic/less/select2-responsive.less"
    "@bower/select2/dist/css/select2.css": "sonatra_gluon_bundle/assetic/less/select2-responsive.less"

    "@bower/sonatra-theme-gluon/less/bootstrap/bootstrap.less": "sonatra_gluon_bundle/assetic/less/bootstrap.less"
    "@bower/sonatra-theme-gluon/css/bootstrap.css": "sonatra_gluon_bundle/assetic/less/bootstrap.less"

    "@bower/sonatra-theme-gluon/less/bootstrap-theme/bootstrap-theme.less": "sonatra_gluon_bundle/assetic/less/bootstrap-theme.less"
    "@bower/sonatra-theme-gluon/css/bootstrap-theme.css": "sonatra_gluon_bundle/assetic/less/bootstrap-theme.less"

    "@bower/sonatra-theme-gluon/less/bootstrap-nav-scroll/bootstrap-nav-scroll.less": "sonatra_gluon_bundle/assetic/less/bootstrap-nav-scroll.less"
    "@bower/sonatra-theme-gluon/css/sonatra-bootstrap-nav-scroll.css": "sonatra_gluon_bundle/assetic/less/bootstrap-nav-scroll.less"

    "@bower/sonatra-theme-gluon/less/bootstrap-panel-collapse/bootstrap-panel-collapse.less": "sonatra_gluon_bundle/assetic/less/bootstrap-panel-collapse.less"
    "@bower/sonatra-theme-gluon/css/sonatra-bootstrap-panel-collapse.css": "sonatra_gluon_bundle/assetic/less/bootstrap-panel-collapse.less"

    "@bower/sonatra-theme-gluon/less/footable/footable.less": "sonatra_gluon_bundle/assetic/less/footable.less"
    "@bower/sonatra-theme-gluon/css/footable.css": "sonatra_gluon_bundle/assetic/less/footable.less"

    "@bower/sonatra-theme-gluon/less/footable-striped/footable-striped.less": "sonatra_gluon_bundle/assetic/less/footable-striped.less"
    "@bower/sonatra-theme-gluon/css/footable-striped.css": "sonatra_gluon_bundle/assetic/less/footable-striped.less"

    "@bower/sonatra-theme-gluon/less/jquery-ripple/jquery-ripple.less": "sonatra_gluon_bundle/assetic/less/jquery-ripple.less"
    "@bower/sonatra-theme-gluon/css/sonatra-jquery-ripple.css": "sonatra_gluon_bundle/assetic/less/jquery-ripple.less"

    "@bower/sonatra-theme-gluon/less/jquery-scroller/jquery-scroller.less": "sonatra_gluon_bundle/assetic/less/jquery-scroller.less"
    "@bower/sonatra-theme-gluon/css/sonatra-jquery-scroller.css": "sonatra_gluon_bundle/assetic/less/jquery-scroller.less"

    "@bower/sonatra-theme-gluon/less/jquery-datetime-picker/jquery-datetime-picker.less": "sonatra_gluon_bundle/assetic/less/jquery-datetime-picker.less"
    "@bower/sonatra-theme-gluon/css/sonatra-jquery-datetime-picker.css": "sonatra_gluon_bundle/assetic/less/jquery-datetime-picker.less"

    "@bower/sonatra-theme-gluon/less/jquery-sidebar/jquery-sidebar.less": "sonatra_gluon_bundle/assetic/less/jquery-sidebar.less"
    "@bower/sonatra-theme-gluon/css/sonatra-jquery-sidebar.css": "sonatra_gluon_bundle/assetic/less/jquery-sidebar.less"

    "@bower/sonatra-theme-gluon/less/jquery-table-pager/jquery-table-pager.less": "sonatra_gluon_bundle/assetic/less/jquery-table-pager.less"
    "@bower/sonatra-theme-gluon/css/sonatra-jquery-table-pager.css": "sonatra_gluon_bundle/assetic/less/jquery-table-pager.less"
    "@bower/sonatra-theme-gluon/less/jquery-table-pager/jquery-table-sort.less": "sonatra_gluon_bundle/assetic/less/jquery-table-sort.less"
    "@bower/sonatra-theme-gluon/css/sonatra-jquery-table-sort.css": "sonatra_gluon_bundle/assetic/less/jquery-table-sort.less"

    "@bower/sonatra-theme-gluon/less/jquery-table-select/jquery-table-select.less": "sonatra_gluon_bundle/assetic/less/jquery-table-select.less"
    "@bower/sonatra-theme-gluon/css/sonatra-jquery-table-select.css": "sonatra_gluon_bundle/assetic/less/jquery-table-select.less"

    "@bower/sonatra-theme-gluon/less/select2-bootstrap-theme/select2-bootstrap-theme.less": "sonatra_gluon_bundle/assetic/less/select2-bootstrap-theme.less"
    "@bower/sonatra-theme-gluon/css/select2-bootstrap-theme.css": "sonatra_gluon_bundle/assetic/less/select2-bootstrap-theme.less"

    "@bower/sonatra-theme-gluon/less/select2-responsive/select2-responsive.less": "sonatra_gluon_bundle/assetic/less/select2-responsive.less"
    "@bower/sonatra-theme-gluon/css/sonatra-select2-responsive.css": "sonatra_gluon_bundle/assetic/less/select2-responsive.less"

    "@bower/sonatra-theme-gluon/less/gluon/gluon.less": "sonatra_gluon_bundle/assetic/less/gluon.less"
    "@bower/sonatra-theme-gluon/css/gluon.css": "sonatra_gluon_bundle/assetic/less/gluon.less"

    "@bower/sonatra-theme-gluon-pjax/css/app-pjax.css": "sonatra_gluon_bundle/assetic/less/app-pjax.less"
    "@bower/sonatra-theme-gluon-pjax/less/app-pjax.less": "sonatra_gluon_bundle/assetic/less/app-pjax.less"
